version: "3.9"
services:
  web:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: db
    ports:
      - 8080:8080
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

volumes:
  postgres: